version: "3.9"

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: remnawave-admin-backend:dev
    env_file:
      - ../.env.example
    environment:
      - APP_ENV=${APP_ENV:-development}
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: remnawave-admin-frontend:dev
    env_file:
      - ../frontend/.env.example
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: remnawave-admin-net
